services:
  api:
    restart: always
    build:
      dockerfile: api.Dockerfile
      context: './'

    volumes:
      - ./apps/admin:/admin
    ports:
      - '3000:3000'

  client:
    build:
      dockerfile: ui.Dockerfile
      context: './'
    depends_on:
      - api # todo: might not be necessary
    volumes:
      - ./apps/functions:/functions
    ports:
      - '4200:4200'
